// <auto-generated />
using BlazorServer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServer.Migrations
{
    [DbContext(typeof(Db))]
    [Migration("20220119163336_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorServer.Test", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("NekiBroj")
                        .HasColumnType("int");

                    b.Property<string>("NekiTekst")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tests");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            NekiBroj = 123,
                            NekiTekst = "abc"
                        },
                        new
                        {
                            Id = -2,
                            NekiBroj = 234,
                            NekiTekst = "dsa"
                        },
                        new
                        {
                            Id = -3,
                            NekiBroj = 345,
                            NekiTekst = "zxc"
                        },
                        new
                        {
                            Id = -4,
                            NekiBroj = 456,
                            NekiTekst = "dfg"
                        },
                        new
                        {
                            Id = -5,
                            NekiBroj = 567,
                            NekiTekst = "rty"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
